INSERT INTO `a_bili_dynamic` VALUES ('161775300', '明日方舟', '479983232648033496', '479988953545543522', '479988846173457805', '479983232648033496', '479682803987943284', '479341272481851719');
INSERT INTO `a_data_version` VALUES ('1');
INSERT INTO `a_group_admin` VALUES ('691029037', '300', '10');
INSERT INTO `a_admin_user` VALUES ('c5ecb54cdb92b19fe7c6c8dca260e69d', '鹤望兰号', '1', '1', '0', '1');

INSERT INTO `a_agent` VALUES ('12F', '2', '公招', '0');
INSERT INTO `a_agent` VALUES ('Castle-3', '1', '公招', '0');
INSERT INTO `a_agent` VALUES ('Lanset-2', '1', '公招', '0');
INSERT INTO `a_agent` VALUES ('THRM-EX', '1', '公招', '0');
INSERT INTO `a_agent` VALUES ('W', '6', '遗愿焰火', '1');
INSERT INTO `a_agent` VALUES ('临光', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('临光', '5', '搅动潮汐之剑', '0');
INSERT INTO `a_agent` VALUES ('乌有', '5', '月隐晦明', '1');
INSERT INTO `a_agent` VALUES ('亚叶', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('伊桑', '4', '凭证兑换', '0');
INSERT INTO `a_agent` VALUES ('伊芙利特', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('傀影', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('傀影', '6', '往日幻象', '0');
INSERT INTO `a_agent` VALUES ('克洛丝', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('凛冬', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('凛冬', '5', '草垛上的风笛声', '0');
INSERT INTO `a_agent` VALUES ('初雪', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('初雪', '5', '银灰色的荣耀', '0');
INSERT INTO `a_agent` VALUES ('刻俄柏', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('刻俄柏', '6', '百种兵器', '0');
INSERT INTO `a_agent` VALUES ('刻刀', '4', '公招', '0');
INSERT INTO `a_agent` VALUES ('刻刀', '4', '往日幻象', '0');
INSERT INTO `a_agent` VALUES ('华法琳', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('卡夫卡', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('卡夫卡', '5', '自由的囚徒', '0');
INSERT INTO `a_agent` VALUES ('卡缇', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('卡达', '4', '君影轻灵', '0');
INSERT INTO `a_agent` VALUES ('卡达', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('古米', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('可颂', '5', '久铸尘铁', '0');
INSERT INTO `a_agent` VALUES ('可颂', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('史尔特尔', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('史尔特尔', '6', '无拘熔火', '0');
INSERT INTO `a_agent` VALUES ('史都华德', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('吽', '5', '地生五金', '1');
INSERT INTO `a_agent` VALUES ('吽', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('嘉维尔', '4', '凭证兑换', '0');
INSERT INTO `a_agent` VALUES ('四月', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('四月', '5', '无拘熔火', '0');
INSERT INTO `a_agent` VALUES ('因陀罗', '5', '公招', '0');
INSERT INTO `a_agent` VALUES ('地灵', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('坚雷', '4', '凭证兑换', '0');
INSERT INTO `a_agent` VALUES ('塞雷娅', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('夕', '6', '月隐晦明', '1');
INSERT INTO `a_agent` VALUES ('夜刀', '2', '公招', '0');
INSERT INTO `a_agent` VALUES ('夜烟', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('夜莺', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('夜魔', '5', '君影轻灵', '0');
INSERT INTO `a_agent` VALUES ('夜魔', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('夜魔', '5', '搅动潮汐之剑', '0');
INSERT INTO `a_agent` VALUES ('天火', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('天火', '5', '热情膨胀爆发', '0');
INSERT INTO `a_agent` VALUES ('奥斯塔', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('奥斯塔', '5', '瑕光微明', '0');
INSERT INTO `a_agent` VALUES ('孑', '4', '不羁逆流', '0');
INSERT INTO `a_agent` VALUES ('孑', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('守林人', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('守林人', '5', '锁与钥的守卫者', '0');
INSERT INTO `a_agent` VALUES ('安哲拉', '5', '不羁逆流', '0');
INSERT INTO `a_agent` VALUES ('安哲拉', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('安德切尔', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('安比尔', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('安比尔', '4', '热情膨胀爆发', '0');
INSERT INTO `a_agent` VALUES ('安洁莉娜', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('安赛尔', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('宴', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('宴', '4', '草垛上的风笛声', '0');
INSERT INTO `a_agent` VALUES ('山', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('山', '6', '自由的囚徒', '0');
INSERT INTO `a_agent` VALUES ('崖心', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('崖心', '5', '银灰色的荣耀', '0');
INSERT INTO `a_agent` VALUES ('嵯峨', '6', '月隐晦明', '1');
INSERT INTO `a_agent` VALUES ('巡林者', '2', '公招', '0');
INSERT INTO `a_agent` VALUES ('巫恋', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('巫恋', '5', '往日幻象', '0');
INSERT INTO `a_agent` VALUES ('布洛卡', '5', '凝电之钻', '0');
INSERT INTO `a_agent` VALUES ('布洛卡', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('年', '6', '地生五金', '1');
INSERT INTO `a_agent` VALUES ('幽灵鲨', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('幽灵鲨', '5', '火舞之人', '0');
INSERT INTO `a_agent` VALUES ('微风', '5', '凭证兑换', '0');
INSERT INTO `a_agent` VALUES ('德克萨斯', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('惊蛰', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('惊蛰', '5', '百种兵器', '0');
INSERT INTO `a_agent` VALUES ('慑砂', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('慑砂', '5', '草垛上的风笛声', '0');
INSERT INTO `a_agent` VALUES ('慑砂', '5', '轮换', '0');
INSERT INTO `a_agent` VALUES ('慕斯', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('拉普兰德', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('拉普兰德', '5', '百种兵器', '0');
INSERT INTO `a_agent` VALUES ('拜松', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('推进之王', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('斑点', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('断崖', '5', '君影轻灵', '0');
INSERT INTO `a_agent` VALUES ('断崖', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('断罪者', '4', '活动', '0');
INSERT INTO `a_agent` VALUES ('斯卡蒂', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('斯卡蒂', '6', '搅动潮汐之剑', '0');
INSERT INTO `a_agent` VALUES ('早露', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('早露', '6', '雪落晨心', '0');
INSERT INTO `a_agent` VALUES ('星极', '5', '久铸尘铁', '0');
INSERT INTO `a_agent` VALUES ('星极', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('星熊', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('星熊', '6', '龙门特别行动专员寻访', '0');
INSERT INTO `a_agent` VALUES ('普罗旺斯', '5', '不羁逆流', '0');
INSERT INTO `a_agent` VALUES ('普罗旺斯', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('普罗旺斯', '5', '火舞之人', '0');
INSERT INTO `a_agent` VALUES ('暗索', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('暗锁', '4', '搅动潮汐之剑', '0');
INSERT INTO `a_agent` VALUES ('暴行', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('月禾', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('月禾', '5', '雾漫荒林', '0');
INSERT INTO `a_agent` VALUES ('月见夜', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('末药', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('杜宾', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('杜林', '2', '公招', '0');
INSERT INTO `a_agent` VALUES ('杰克', '4', '勿忘我', '1');
INSERT INTO `a_agent` VALUES ('杰克', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('杰西卡', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('松果', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('松果', '4', '自由的囚徒', '0');
INSERT INTO `a_agent` VALUES ('极境', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('极境', '5', '无拘熔火', '0');
INSERT INTO `a_agent` VALUES ('极境', '5', '遗愿焰火', '1');
INSERT INTO `a_agent` VALUES ('柏喙', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('格劳克斯', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('格劳克斯', '5', '深夏的守夜人', '0');
INSERT INTO `a_agent` VALUES ('格拉尼', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('格雷伊', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('格雷伊', '4', '鞘中赤红', '0');
INSERT INTO `a_agent` VALUES ('桃金娘', '4', '久铸尘铁', '0');
INSERT INTO `a_agent` VALUES ('桃金娘', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('梅', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('梅', '4', '锁与钥的守卫者', '0');
INSERT INTO `a_agent` VALUES ('梅尔', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('梓兰', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('棘刺', '6', '不羁逆流', '0');
INSERT INTO `a_agent` VALUES ('棘刺', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('森蚺', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('森蚺', '6', '燃钢之心', '0');
INSERT INTO `a_agent` VALUES ('槐琥', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('槐琥', '5', '锁与钥的守卫者', '0');
INSERT INTO `a_agent` VALUES ('泡普卡', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('泡泡', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('泡泡', '4', '瑕光微明', '0');
INSERT INTO `a_agent` VALUES ('波登可', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('波登可', '4', '雪落晨心', '0');
INSERT INTO `a_agent` VALUES ('泥岩', '6', '勿忘我', '1');
INSERT INTO `a_agent` VALUES ('泥岩', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('流星', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('深海色', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('清流', '4', '活动', '0');
INSERT INTO `a_agent` VALUES ('清道夫', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('温蒂', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('温蒂', '6', '遗愿焰火', '1');
INSERT INTO `a_agent` VALUES ('火神', '5', '公招', '0');
INSERT INTO `a_agent` VALUES ('灰喉', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('灰喉', '5', '热情膨胀爆发', '0');
INSERT INTO `a_agent` VALUES ('灰烬', '6', '进攻、防守、战术交汇', '1');
INSERT INTO `a_agent` VALUES ('炎客', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('炎熔', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('煌', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('煌', '6', '热情膨胀爆发', '0');
INSERT INTO `a_agent` VALUES ('煌', '6', '轮换', '0');
INSERT INTO `a_agent` VALUES ('燧石', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('燧石', '5', '燃钢之心', '0');
INSERT INTO `a_agent` VALUES ('特米米', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('狮蝎', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('猎蜂', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('猎蜂', '4', '搅动潮汐之剑', '0');
INSERT INTO `a_agent` VALUES ('玫兰莎', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('瑕光', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('瑕光', '6', '瑕光微明', '0');
INSERT INTO `a_agent` VALUES ('白金', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('白金', '5', '瑕光微明', '0');
INSERT INTO `a_agent` VALUES ('白雪', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('白面鸮', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('白面鸮', '5', '往日幻象', '0');
INSERT INTO `a_agent` VALUES ('真理', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('真理', '5', '雪落晨心', '0');
INSERT INTO `a_agent` VALUES ('石棉', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('石棉', '5', '雾漫荒林', '0');
INSERT INTO `a_agent` VALUES ('砾', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('稀音', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('空', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('空爆', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('米格鲁', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('絮雨', '5', '勿忘我', '1');
INSERT INTO `a_agent` VALUES ('絮雨', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('红', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('红云', '4', '冰封原野', '0');
INSERT INTO `a_agent` VALUES ('红云', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('红豆', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('缠丸', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('翎羽', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('能天使', '6', '凝电之钻', '0');
INSERT INTO `a_agent` VALUES ('能天使', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('艾斯黛尔', '4', '公招', '0');
INSERT INTO `a_agent` VALUES ('艾雅法拉', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('艾雅法拉', '6', '火舞之人', '0');
INSERT INTO `a_agent` VALUES ('芙兰卡', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('芙蓉', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('芬', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('芳汀', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('芳汀', '4', '无拘熔火', '0');
INSERT INTO `a_agent` VALUES ('苇草', '5', '凝电之钻', '0');
INSERT INTO `a_agent` VALUES ('苇草', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('苇草', '5', '轮换', '0');
INSERT INTO `a_agent` VALUES ('苏苏洛', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('苏苏洛', '5', '深夏的守夜人', '0');
INSERT INTO `a_agent` VALUES ('苦艾', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('莫斯提马', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('莫斯提马', '6', '锁与钥的守卫者', '0');
INSERT INTO `a_agent` VALUES ('莱恩哈特', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('莱恩哈特', '5', '轮换', '0');
INSERT INTO `a_agent` VALUES ('莱恩哈特', '5', '雪落晨心', '0');
INSERT INTO `a_agent` VALUES ('蓝毒', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('蓝毒', '5', '深夏的守夜人', '0');
INSERT INTO `a_agent` VALUES ('薄绿', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('蛇屠箱', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('蜜蜡', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('蜜蜡', '5', '流沙涡旋', '0');
INSERT INTO `a_agent` VALUES ('角峰', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('角峰', '4', '银灰色的荣耀', '0');
INSERT INTO `a_agent` VALUES ('讯使', '4', '凭证兑换', '0');
INSERT INTO `a_agent` VALUES ('诗怀雅', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('诗怀雅', '5', '鞘中赤红', '0');
INSERT INTO `a_agent` VALUES ('调香师', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('贾维', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('贾维', '5', '流沙涡旋', '0');
INSERT INTO `a_agent` VALUES ('赫拉格', '6', '久铸尘铁', '0');
INSERT INTO `a_agent` VALUES ('赫拉格', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('赫默', '5', '冰封原野', '0');
INSERT INTO `a_agent` VALUES ('赫默', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('赫默', '5', '自由的囚徒', '0');
INSERT INTO `a_agent` VALUES ('远山', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('迷迭香', '6', '勿忘我', '1');
INSERT INTO `a_agent` VALUES ('送葬人', '5', '冰封原野', '0');
INSERT INTO `a_agent` VALUES ('送葬人', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('酸糖', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('酸糖', '4', '燃钢之心', '0');
INSERT INTO `a_agent` VALUES ('铃兰', '6', '君影轻灵', '0');
INSERT INTO `a_agent` VALUES ('铃兰', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('铃兰', '6', '轮换', '0');
INSERT INTO `a_agent` VALUES ('银灰', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('银灰', '6', '银灰色的荣耀', '0');
INSERT INTO `a_agent` VALUES ('铸铁', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('锡兰', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('闪击', '5', '进攻、防守、战术交汇', '1');
INSERT INTO `a_agent` VALUES ('闪灵', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('阿', '1', '地生五金', '1');
INSERT INTO `a_agent` VALUES ('阿', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('阿消', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('阿米娅', '5', '初始', '0');
INSERT INTO `a_agent` VALUES ('陈', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('陈', '6', '鞘中赤红', '0');
INSERT INTO `a_agent` VALUES ('陨星', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('陨星', '5', '燃钢之心', '0');
INSERT INTO `a_agent` VALUES ('陨星', '5', '龙门特别行动专员寻访', '0');
INSERT INTO `a_agent` VALUES ('雪雉', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('雷蛇', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('雷蛇', '5', '龙门特别行动专员寻访', '0');
INSERT INTO `a_agent` VALUES ('霜华', '5', '进攻、防守、战术交汇', '1');
INSERT INTO `a_agent` VALUES ('霜叶', '4', '常规', '0');
INSERT INTO `a_agent` VALUES ('鞭刃', '5', '活动', '0');
INSERT INTO `a_agent` VALUES ('风笛', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('风笛', '6', '草垛上的风笛声', '0');
INSERT INTO `a_agent` VALUES ('食铁兽', '5', '常规', '0');
INSERT INTO `a_agent` VALUES ('食铁兽', '5', '鞘中赤红', '0');
INSERT INTO `a_agent` VALUES ('香草', '3', '常规', '0');
INSERT INTO `a_agent` VALUES ('麦哲伦', '6', '冰封原野', '0');
INSERT INTO `a_agent` VALUES ('麦哲伦', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('黑', '6', '常规', '0');
INSERT INTO `a_agent` VALUES ('黑', '6', '深夏的守夜人', '0');
INSERT INTO `a_agent` VALUES ('黑角', '2', '公招', '0');
INSERT INTO `a_agent` VALUES ('异客', '6', '沙海过客', '1');
INSERT INTO `a_agent` VALUES ('熔泉', '5', '沙海过客', '1');
INSERT INTO `a_agent` VALUES ('慑砂', '5', '沙海过客', '1');
INSERT INTO `a_agent` VALUES ('异客', '6', '常规', '1');
INSERT INTO `a_agent` VALUES ('熔泉', '5', '常规', '1');

INSERT INTO `a_nick_name` VALUES ('42', '史尔特尔');
INSERT INTO `a_nick_name` VALUES ('42姐', '史尔特尔');
INSERT INTO `a_nick_name` VALUES ('ash', '灰烬');
INSERT INTO `a_nick_name` VALUES ('d32钢', '星极');
INSERT INTO `a_nick_name` VALUES ('ff0', '华法琳');
INSERT INTO `a_nick_name` VALUES ('五速无头怪', '灰烬');
INSERT INTO `a_nick_name` VALUES ('充电宝', '雷蛇');
INSERT INTO `a_nick_name` VALUES ('先蒂', '斯卡蒂');
INSERT INTO `a_nick_name` VALUES ('克天使', '克洛丝');
INSERT INTO `a_nick_name` VALUES ('兔兔', '阿米娅');
INSERT INTO `a_nick_name` VALUES ('关二爷', '波登可');
INSERT INTO `a_nick_name` VALUES ('刻狗', '刻俄柏');
INSERT INTO `a_nick_name` VALUES ('前夫哥', '银灰');
INSERT INTO `a_nick_name` VALUES ('剑兔', '近卫阿米娅');
INSERT INTO `a_nick_name` VALUES ('医疗小车', 'Lancet-2');
INSERT INTO `a_nick_name` VALUES ('叉烧猫', '诗怀雅');
INSERT INTO `a_nick_name` VALUES ('吉祥物', '诗怀雅');
INSERT INTO `a_nick_name` VALUES ('哥伦布', '麦哲伦');
INSERT INTO `a_nick_name` VALUES ('塞妈', '塞雷娅');
INSERT INTO `a_nick_name` VALUES ('塞爹', '塞雷娅');
INSERT INTO `a_nick_name` VALUES ('太子爷', '12f');
INSERT INTO `a_nick_name` VALUES ('姑妈', '鞭刃');
INSERT INTO `a_nick_name` VALUES ('客师傅', '异客');
INSERT INTO `a_nick_name` VALUES ('富婆猫猫头', '杰西卡');
INSERT INTO `a_nick_name` VALUES ('小僧', '嵯峨');
INSERT INTO `a_nick_name` VALUES ('小刻', '刻俄柏');
INSERT INTO `a_nick_name` VALUES ('小火山', '安洁莉娜');
INSERT INTO `a_nick_name` VALUES ('小火龙', '伊芙利特');
INSERT INTO `a_nick_name` VALUES ('小羊', '艾雅法拉');
INSERT INTO `a_nick_name` VALUES ('小老虎', '诗怀雅');
INSERT INTO `a_nick_name` VALUES ('小莫', '莫斯提马');
INSERT INTO `a_nick_name` VALUES ('弦子姐 ', '空弦');
INSERT INTO `a_nick_name` VALUES ('弦弦', '空弦');
INSERT INTO `a_nick_name` VALUES ('德狗', '德克萨斯');
INSERT INTO `a_nick_name` VALUES ('拉狗', '拉普兰德');
INSERT INTO `a_nick_name` VALUES ('早子姐', '早露');
INSERT INTO `a_nick_name` VALUES ('枣子姐', '早露');
INSERT INTO `a_nick_name` VALUES ('桃子', '桃金娘');
INSERT INTO `a_nick_name` VALUES ('洁哥', '安洁莉娜');
INSERT INTO `a_nick_name` VALUES ('流泪猫猫头', '杰西卡');
INSERT INTO `a_nick_name` VALUES ('海哲拉', '安哲拉');
INSERT INTO `a_nick_name` VALUES ('海猫', '安哲拉');
INSERT INTO `a_nick_name` VALUES ('火子姐', '天火');
INSERT INTO `a_nick_name` VALUES ('煌喵喵', '煌');
INSERT INTO `a_nick_name` VALUES ('狐萝卜', '铃兰');
INSERT INTO `a_nick_name` VALUES ('猛男', '安塞尔');
INSERT INTO `a_nick_name` VALUES ('玫剑圣', '玫兰莎');
INSERT INTO `a_nick_name` VALUES ('瓜天使', '安比尔');
INSERT INTO `a_nick_name` VALUES ('白咕咕', '白面鸮');
INSERT INTO `a_nick_name` VALUES ('白送', '拜松');
INSERT INTO `a_nick_name` VALUES ('穷苦学生', '雪雉');
INSERT INTO `a_nick_name` VALUES ('粉肠龙', '陈');
INSERT INTO `a_nick_name` VALUES ('罗德岛之光', '铃兰');
INSERT INTO `a_nick_name` VALUES ('老爷子', '赫拉格');
INSERT INTO `a_nick_name` VALUES ('考哥', '异客');
INSERT INTO `a_nick_name` VALUES ('胖狐狸', '芙兰卡');
INSERT INTO `a_nick_name` VALUES ('胜利姐', '月禾');
INSERT INTO `a_nick_name` VALUES ('自爆小车', 'THRM-EX');
INSERT INTO `a_nick_name` VALUES ('茄子', '安比尔');
INSERT INTO `a_nick_name` VALUES ('莱茵哈特', '莱恩哈特');
INSERT INTO `a_nick_name` VALUES ('蒂蒂', '温蒂');
INSERT INTO `a_nick_name` VALUES ('西蓝花', '锡兰');
INSERT INTO `a_nick_name` VALUES ('豆子龙', '红豆');
INSERT INTO `a_nick_name` VALUES ('近卫小车', 'Castle-3');
INSERT INTO `a_nick_name` VALUES ('银老板', '银灰');
INSERT INTO `a_nick_name` VALUES ('闪盾', '闪击');
INSERT INTO `a_nick_name` VALUES ('阿米驴', '阿米娅');
INSERT INTO `a_nick_name` VALUES ('陈sir', '陈');
INSERT INTO `a_nick_name` VALUES ('陈辉洁', '陈');
INSERT INTO `a_nick_name` VALUES ('雷子姐', '惊蛰');
INSERT INTO `a_nick_name` VALUES ('香香鹿', '讯使');
INSERT INTO `a_nick_name` VALUES ('鬼姐', '星熊');
INSERT INTO `a_nick_name` VALUES ('鲨鲨', '幽灵鲨');
INSERT INTO `a_nick_name` VALUES ('鸡精', '极境');
INSERT INTO `a_nick_name` VALUES ('鸡翅', '棘刺');
INSERT INTO `a_nick_name` VALUES ('麦当劳', '麦哲伦');
INSERT INTO `a_nick_name` VALUES ('麦迪文', '麦哲伦');
INSERT INTO `a_nick_name` VALUES ('龙警察', '陈');
INSERT INTO `a_nick_name` VALUES ('龟龟', '蛇屠箱');
